// <auto-generated />
using GGCasualNote.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGCasualNote.Migrations
{
    [DbContext(typeof(GgNoteContext))]
    [Migration("20240529200956_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("GGCasualNote.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GGCasualNote.Models.ComboNote", b =>
                {
                    b.Property<int>("ComboNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComboString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FootageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteContext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComboNoteId");

                    b.ToTable("ComboNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
